export const routes = {
  HOME: '/',
  HOME_PAGE: '/home',
  SIGN_IN: '/sign_in',
  REGISTRATION: '/registration',
  MAIN: '/main',
  CREATE_AD: '/create_ad',
  MY_ADS: '/my_ads',
  EMPTY_PAGE: '/empty',
  PROFILE: '/profile',
  PRODUCTS: '/products',
  QUADCOPTERS: '/quadcopters',
  PAY: '/pay',
  DRONS: '/drons',
  SETS: '/sets',
  CONTACTS: '/contacts',
  CART: '/cart',
  CAMERAS: '/cameras',
  USERS: '/users',
  ORDERS: '/orders',
};
